### ISSUE TITLE
Crash - Ticking entity (BlockUnstable)

### ISSUE THREAD

**Issue by Velocihater** [Hugman76/Mubble#25]
**Describe the bug**
https://hastebin.com/ulemivehug.http

**How To Reproduce**
Something to do with a creeper and Unstable Stone/Rewind Block.

**Expected behavior**
Game should not crash.

**Comment by azaquaz** [comment]
I've had this same crash. It happens when a mob is on top of an unstable stone block. It also doesn't happen when the only mod installed is Mubble, but it would be a lot of work to go through all my mods and disable them one by one to find the mod causing the issue. Here are two more crash reports, once with a modded mob and once with a vanilla zombie.

https://paste.dimdev.org/idayeyimam.mccrash
https://paste.dimdev.org/wafifezubu.mccrash

Are there any mods I have installed that may be causing the issue?

**Comment by Hugman76** [comment]
I think the way I made the system about timing is actually wrong and is surely made by Mubble itself, and not by other mods. I also had this crash one time. I might lock the feature to players only.

**Comment by SirBlockles** [comment]
Can confirm this issue is [still happening](https://gist.github.com/SirBlockles/faed63f039d4484fc8d9e9ca2a0b81ad) (mobs from the tf2 mod seem to have an affinity for triggering it) in 1.3-pre5. It seems that once the server crashes with the issue once, it can be loaded again just fine without corrupting the world. Maybe the block breaks under the entity even though it crashes anyway?

**Comment by Velocihater** [comment]
Yup still happening :(

**Comment by Zoofule** [comment]
Also can confirm it is still happening, was curious if there was a config that would let me disable that one block until that item is fixed?

**Comment by Hugman76** [comment]
Woops, sounds like I haven't got the notifications for those updates, sorry about that.
I will push another version soon and will lock the blocks that use this class to players only.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v**1.3**.
